######### Cadastro de Mensagem
POST http://127.0.0.1:3333/messages HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.pxFayb1qksc3T2Yr-CmifWmZDWKGMFsUe6Qgi4RoLkj5pVwfFbKSq96Lss9C
{
    "title": "Olá",
    "message": "Segunda mensagem do chat!"
}

######### Listar todos as Mensagens
GET http://127.0.0.1:3333/messages HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.pxFayb1qksc3T2Yr-CmifWmZDWKGMFsUe6Qgi4RoLkj5pVwfFbKSq96Lss9C

######### Listar Mensagem específica
GET http://127.0.0.1:3333/messages/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.pxFayb1qksc3T2Yr-CmifWmZDWKGMFsUe6Qgi4RoLkj5pVwfFbKSq96Lss9C

######### Alterar Mensagem
PUT http://127.0.0.1:3333/messages/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.pxFayb1qksc3T2Yr-CmifWmZDWKGMFsUe6Qgi4RoLkj5pVwfFbKSq96Lss9C
{
    "title": "Olá",
    "message": "Mensagem do chat alterada!"
}

######### Apagar Mensagem
DELETE http://127.0.0.1:3333/messages/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer MQ.pxFayb1qksc3T2Yr-CmifWmZDWKGMFsUe6Qgi4RoLkj5pVwfFbKSq96Lss9C
